### PR TITLE
Notification param format

### PR DESCRIPTION
**Pull request by renetapopova**
I think we are not using backticks in a consistent way in the code. So, maybe we should reconsider their usage and leave them just for the docs.

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-192.surge.sh

Updated pages:
- [List of all server notification codes](https://neo4j-docs-status-codes-192.surge.sh/status-codes/5/notifications/all-notifications)

**Comment by Lojjs** [comment]
> I think we are not using backticks in a consistent way in the code. So, maybe we should reconsider their usage and leave them just for the docs.

I have not looked properly at the details yet. I know this is rather messy for notifications, hopefully a bit better for the new errors. We can change the status description in the code but not the old description because those are breaking. The formatting of docs we can change however we like of course

**Comment by renetapopova** [comment]
> > I think we are not using backticks in a consistent way in the code. So, maybe we should reconsider their usage and leave them just for the docs.
> 
> I have not looked properly at the details yet. I know this is rather messy for notifications, hopefully a bit better for the new errors. We can change the status description in the code but not the old description because those are breaking. The formatting of docs we can change however we like of course

Let's keep the consistency only for the docs.

**Review by Lojjs — APPROVED** [review]
Based on our discussion I think this looks fine

**Pull request merged**
