### PR TITLE
Swap some examples tabs and fix some bugs

### PR DESCRIPTION
**Pull request by renetapopova**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-239.surge.sh

Updated pages:
- [List of notification codes](https://neo4j-docs-status-codes-239.surge.sh/status-codes/2025.01/notifications/all-notifications)

**Review by NataliaIvakina — COMMENTED** [review]
Everything looks fine but starting with the ex.27 (line 1895, Using a renamed or deprecated procedure), the first tab is 'Neo4j code' despite the fact that in the code the order is opposite. I don't understand why.

Another questions is about titles: Will we change 'category' to 'notifications' in 'Unsupported category', 'Security category', 'Topology category', and 'Schema category'?

**Comment by renetapopova** [comment]
> Everything looks fine but starting with the ex.27 (line 1895, Using a renamed or deprecated procedure), the first tab is still 'Neo4j code' despite the fact that in the code the order is opposite. I don't understand why.
> 
> Another questions is about titles: Will we change 'category' to 'notifications' in 'Unsupported category', 'Security category', 'Topology category', and 'Schema category'?

On the first question, it's a bug. We need to ask DocOps to fix it.
And on the second question -> Good catch. I'll fix that in this PR. Thanks a lot!

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-239.surge.sh

Updated pages:
- [List of notification codes](https://neo4j-docs-status-codes-239.surge.sh/status-codes/2025.01/notifications/all-notifications)

**Pull request merged**
