### PR TITLE
Union ordering no longer deprecated

### PR DESCRIPTION
**Pull request by gem-neo4j**
We decided to undeprecate this :)

related to https://github.com/neo-technology/neo4j/pull/28207

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-219.surge.sh

Updated pages:
- [List of all server notification codes](https://neo4j-docs-status-codes-219.surge.sh/status-codes/5/notifications/all-notifications)

**Comment by NataliaIvakina** [comment]
@gem-neo4j, is this undeprecation for 5.26 LTS release?

**Review by NataliaIvakina — APPROVED** [review]
I think everything looks good. If I understood everything correctly, the only thing to do here is to remove the example.
Also, I suppose you have to update the Cypher manual. This deprecation is mentioned [here](https://neo4j.com/docs/cypher-manual/current/deprecations-additions-removals-compatibility/#cypher-deprecations-additions-removals-5.5).

**Comment by NataliaIvakina** [comment]
> The warning message will show up in the Cypher 5.x versions before 5.26, do you think we should just remove it from there completely or add an update in 5.26 saying the deprecation has been removed?

I think you should add an update in 5.26. Don't remove the deprecation from the list because it is true for those who use Neo4j 5.5-5.25. 

Probably in the Status Codes, we also have to add a note or a line to the page https://neo4j.com/docs/status-codes/current/changelogs/. @renetapopova, what do you think?

**Comment by gem-neo4j** [comment]
Like this? https://github.com/neo4j/docs-cypher/pull/1113

**Comment by NataliaIvakina** [comment]
> Like this? [neo4j/docs-cypher#1113](https://github.com/neo4j/docs-cypher/pull/1113)

Yes, this looks good (from my side 😄). I'm sure Jens will help you with reviewing the PR for the Cypher manual

**Comment by renetapopova** [comment]
> > The warning message will show up in the Cypher 5.x versions before 5.26, do you think we should just remove it from there completely or add an update in 5.26 saying the deprecation has been removed?
> 
> I think you should add an update in 5.26. Don't remove the deprecation from the list because it is true for those who use Neo4j 5.5-5.25.
> 
> Probably in the Status Codes, we also have to add a note or a line to the page https://neo4j.com/docs/status-codes/current/changelogs/. @renetapopova, what do you think?

I don't think we can just remove the example and the deprecation. This is a valid deprecation until 5.26. Also, @Lojjs, isn't the removal of this deprecation a breaking change? And yes, we should also update **Changes to status codes per Neo4j version** to say that this deprecation has been removed in 5.26 or something in this line of thought.

**Review by renetapopova — CHANGES_REQUESTED** [review]

**Comment by Lojjs** [comment]
> Also, @Lojjs, isn't the removal of this deprecation a breaking change?

No idea 🤷 It is PM (Valerio I believe) that has decided that this deprecation should be removed. I would maybe let PM decide how to handle the documentation-wise as well. I do not have any strong opinon about this

**Comment by NataliaIvakina** [comment]
But do we provide a complete list of all examples for deprecated features here? Union reordering just falls under the notification code `Neo.ClientNotification.Statement.FeatureDeprecationWarning`, and starting from 5.26 you won't get this warning any longer. The Cypher manual documents this, not the Status Codes. There are no changes to the Neo4j notification code or GQLstatus code.

**Comment by renetapopova** [comment]
Adding Valerio's suggestion here for completeness:
"Add a special subsection called 'Withdrawn deprecations' and put those examples there?
We could write a short intro along the lines:
This section lists features deprecated during this release train that have been un-deprecated after cost/benefit analysis and user conversations. These features will not be withdrawn and will continue to be supported."

**Comment by renetapopova** [comment]
Replaced by #224

**Pull request closed without merging**
