### PR TITLE
Add a warning that parsing status descriptions is not recommended

### PR DESCRIPTION
**Pull request by renetapopova**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-228.surge.sh

Updated pages:
- [List of GQLSTATUS error codes](https://neo4j-docs-status-codes-228.surge.sh/status-codes/5/errors/gql-errors)
- [List of notification codes](https://neo4j-docs-status-codes-228.surge.sh/status-codes/5/notifications/all-notifications)

**Review by Lojjs — CHANGES_REQUESTED** [review]
Nice, I just think we should write out the full "status description" so people are not confusing it with the old description for notifications

**Comment by renetapopova** [comment]
> Nice, I just think we should write out the full "status description" so people are not confusing it with the old description for notifications

Yes, you're right.

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-228.surge.sh

Updated pages:
- [List of GQLSTATUS error codes](https://neo4j-docs-status-codes-228.surge.sh/status-codes/5/errors/gql-errors)
- [List of notification codes](https://neo4j-docs-status-codes-228.surge.sh/status-codes/5/notifications/all-notifications)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-228.surge.sh

Updated pages:
- [List of GQLSTATUS error codes](https://neo4j-docs-status-codes-228.surge.sh/status-codes/5/errors/gql-errors)
- [List of notification codes](https://neo4j-docs-status-codes-228.surge.sh/status-codes/5/notifications/all-notifications)

**Review by Lojjs — APPROVED** [review]

**Pull request merged**
