### PR TITLE
Swap the places of the legacy and the GQL code tab examples

### PR DESCRIPTION
**Pull request by renetapopova**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-205.surge.sh

Updated pages:
- [List of all server notification codes](https://neo4j-docs-status-codes-205.surge.sh/status-codes/5/notifications/all-notifications)
- [Server notifications](https://neo4j-docs-status-codes-205.surge.sh/status-codes/5/notifications)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-status-codes-205.surge.sh

Updated pages:
- [List of all server notification codes](https://neo4j-docs-status-codes-205.surge.sh/status-codes/5/notifications/all-notifications)
- [Server notifications](https://neo4j-docs-status-codes-205.surge.sh/status-codes/5/notifications)

**Comment by renetapopova** [comment]
@Lojjs, I think you're changes look good.

**Review by Lojjs — APPROVED** [review]
I like your changes too :) Feel free to merge this one.

**Pull request merged**
